source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LVModalQueue_Example', :exclusive => true do
  pod "LVModalQueue", :path => "../"
end

target 'LVModalQueue_Tests', :exclusive => true do
  pod "LVModalQueue", :path => "../"

  
end
