source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'LVModalQueue_Example' do
  pod "LVModalQueue", :path => "../"
end

target 'LVModalQueue_Tests' do
  pod "LVModalQueue", :path => "../"
end
